# This is a basic workflow to help you get started with Actions

name: pytest

permissions: write-all

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pytest"
  pytest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Test with pytest on Docker
        run: |
          touch ./app/.env
          echo DB_HOST=db >> .env
          echo MYSQL_USER=docker_dev >> .env
          echo MYSQL_PASSWORD=cRH1eL4GbNZkFXlk >> .env
          echo BIND-ADDRESS=0.0.0.0 >> .env
          echo MYSQL_RANDOM_ROOT_PASSWORD=yes >> .env
          echo MYSQL_DATABASE=quaint-app >> .env
          docker-compose up -d
          docker-compose exec -T app bash /app/wait-for-it.sh db:3306 -t 60 -- pytest --cov --junitxml=/app/app/test/pytest.xml --cov-report=term-missing:skip-covered > ./pytest-coverage.txt

      - name: Create Coverage Comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./app/test/pytest.xml

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.3.0
        with:
          auth: ${{ secrets.BADGE_GIST }} # 名前は適宜変更:手順5で決めたトークン名
          gistID: 81370c9284b6c64224021c2c6520c2e3 #先ほど控えたGist ID
          # 以降はコピペ可
          # cerverageCommentはPytest Coverage CommentのID
          # 書き換えた場合は変更が必要
          filename: pytest-coverage-comment.json
          label: Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: python
